//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CotizaReales : ICotizacion
{
	public string CotizarMoneda(string uri)
	{
        System.ArgumentException argEx = new System.ArgumentException("401 no authorized de http", "index");
        throw argEx;
	}

}

