//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;

public class CotizaDolar : ICotizacion
{
	public string CotizarMoneda(string uri)
	{
        HttpWebRequest request = WebRequest.Create("http://www.bancoprovincia.com.ar/Principal/dolar") as HttpWebRequest;
        try
        {
            using (HttpWebResponse response = request.GetResponse() as HttpWebResponse)
            {
                if (response.StatusCode != HttpStatusCode.OK)
                    throw new Exception(String.Format(
                    "Server error (HTTP {0}: {1}).",
                    response.StatusCode,
                    response.StatusDescription));
                StreamReader reader = new StreamReader(response.GetResponseStream());
                string data = reader.ReadToEnd();

                return data;
            }
        }
        catch (Exception ex)
        {
            throw new Exception("Error consumiendo el servicio ", ex );
        }
    }
}

